# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MMCameraLibraryUtils' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MMCameraLibraryUtils
  pod 'MBProgressHUD', '~> 0.8'
end
